-- MySQL Script generated by MySQL Workbench
-- seg 20 mar 2023 20:42:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ministock
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ministock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ministock` DEFAULT CHARACTER SET utf8 ;
USE `ministock` ;

-- -----------------------------------------------------
-- Table `ministock`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ministock`.`Produto` (
  `codProduto` INT NOT NULL AUTO_INCREMENT,
  `codigoBarras` VARCHAR(45) NOT NULL,
  `nomeProduto` VARCHAR(80) NOT NULL,
  `precoCusto` DOUBLE NOT NULL,
  `precoVenda` DOUBLE NOT NULL,
  `qtdAtualEstoque` INT NOT NULL,
  `imagem` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ministock`.`Bairro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ministock`.`Bairro` (
  `idBairro` INT NOT NULL AUTO_INCREMENT,
  `nomeBairro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBairro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ministock`.`UnidadeFederativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ministock`.`UnidadeFederativa` (
  `idUnidadeFederativa` INT NOT NULL AUTO_INCREMENT,
  `siglaUF` VARCHAR(2) NOT NULL,
  `nomeUF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUnidadeFederativa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ministock`.`Municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ministock`.`Municipio` (
  `idMunicipio` INT NOT NULL AUTO_INCREMENT,
  `nomeMunicipio` VARCHAR(45) NOT NULL,
  `UnidadeFederativa_idUnidadeFederativa` INT NOT NULL,
  PRIMARY KEY (`idMunicipio`),
  INDEX `fk_Municipio_UnidadeFederativa_idx` (`UnidadeFederativa_idUnidadeFederativa` ASC),
  CONSTRAINT `fk_Municipio_UnidadeFederativa`
    FOREIGN KEY (`UnidadeFederativa_idUnidadeFederativa`)
    REFERENCES `ministock`.`UnidadeFederativa` (`idUnidadeFederativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ministock`.`TipoLogradouro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ministock`.`TipoLogradouro` (
  `idTipoLogradouro` INT NOT NULL AUTO_INCREMENT,
  `nomeTipoLogradouro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoLogradouro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ministock`.`Logradouro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ministock`.`Logradouro` (
  `idLogradouro` INT NOT NULL AUTO_INCREMENT,
  `nomeLogradouro` VARCHAR(45) NOT NULL,
  `TipoLogradouro_idTipoLogradouro` INT NOT NULL,
  PRIMARY KEY (`idLogradouro`),
  INDEX `fk_Logradouro_TipoLogradouro1_idx` (`TipoLogradouro_idTipoLogradouro` ASC),
  CONSTRAINT `fk_Logradouro_TipoLogradouro1`
    FOREIGN KEY (`TipoLogradouro_idTipoLogradouro`)
    REFERENCES `ministock`.`TipoLogradouro` (`idTipoLogradouro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ministock`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ministock`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `cepEndereco` VARCHAR(45) NOT NULL,
  `Bairro_idBairro` INT NOT NULL,
  `Municipio_idMunicipio` INT NOT NULL,
  `Logradouro_idLogradouro` INT NOT NULL,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_Endereco_Bairro1_idx` (`Bairro_idBairro` ASC),
  INDEX `fk_Endereco_Municipio1_idx` (`Municipio_idMunicipio` ASC),
  INDEX `fk_Endereco_Logradouro1_idx` (`Logradouro_idLogradouro` ASC),
  CONSTRAINT `fk_Endereco_Bairro1`
    FOREIGN KEY (`Bairro_idBairro`)
    REFERENCES `ministock`.`Bairro` (`idBairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Municipio1`
    FOREIGN KEY (`Municipio_idMunicipio`)
    REFERENCES `ministock`.`Municipio` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Logradouro1`
    FOREIGN KEY (`Logradouro_idLogradouro`)
    REFERENCES `ministock`.`Logradouro` (`idLogradouro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ministock`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ministock`.`Fornecedor` (
  `codFornecedor` INT NOT NULL AUTO_INCREMENT,
  `nomeFornecedor` VARCHAR(80) NOT NULL,
  `cnpj` VARCHAR(20) NOT NULL,
  `nroEndereco` INT NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`codFornecedor`),
  INDEX `fk_Fornecedor_Endereco1_idx` (`Endereco_idEndereco` ASC),
  CONSTRAINT `fk_Fornecedor_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `ministock`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ministock`.`NotaCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ministock`.`NotaCompra` (
  `nroNotaCompra` INT NOT NULL AUTO_INCREMENT,
  `dataCompra` DATE NOT NULL,
  `Fornecedor_codFornecedor` INT NOT NULL,
  `totalCompra` DOUBLE NOT NULL,
  `descontoCompra` DOUBLE NOT NULL,
  `valorLiquidoCompra` DOUBLE NOT NULL,
  PRIMARY KEY (`nroNotaCompra`),
  INDEX `fk_NotaCompra_Fornecedor1_idx` (`Fornecedor_codFornecedor` ASC),
  CONSTRAINT `fk_NotaCompra_Fornecedor1`
    FOREIGN KEY (`Fornecedor_codFornecedor`)
    REFERENCES `ministock`.`Fornecedor` (`codFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ministock`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ministock`.`Cliente` (
  `codCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `cnpj` VARCHAR(20) NOT NULL,
  `isPessoaFisica` TINYINT NOT NULL,
  `telefoneCliente` VARCHAR(45) NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`codCliente`),
  INDEX `fk_Cliente_Endereco1_idx` (`Endereco_idEndereco` ASC),
  CONSTRAINT `fk_Cliente_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `ministock`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ministock`.`NotaVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ministock`.`NotaVenda` (
  `nroNotaVenda` INT NOT NULL AUTO_INCREMENT,
  `dataVenda` DATE NOT NULL,
  `Cliente_codCliente` INT NOT NULL,
  `totalVenda` DOUBLE NOT NULL,
  `descontoVenda` DOUBLE NOT NULL,
  `valorLiquidoVenda` DOUBLE NOT NULL,
  `isDinheiro` TINYINT NOT NULL,
  `Endereco_idEndereco` INT NOT NULL,
  PRIMARY KEY (`nroNotaVenda`),
  INDEX `fk_NotaVenda_Cliente1_idx` (`Cliente_codCliente` ASC),
  INDEX `fk_NotaVenda_Endereco1_idx` (`Endereco_idEndereco` ASC),
  CONSTRAINT `fk_NotaVenda_Cliente1`
    FOREIGN KEY (`Cliente_codCliente`)
    REFERENCES `ministock`.`Cliente` (`codCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NotaVenda_Endereco1`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `ministock`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ministock`.`ItemCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ministock`.`ItemCompra` (
  `Produto_codProduto` INT NOT NULL,
  `NotaCompra_nroNotaCompra` INT NOT NULL,
  `qtdItemCompra` INT NOT NULL,
  `valorItemCompra` DOUBLE NOT NULL,
  PRIMARY KEY (`Produto_codProduto`, `NotaCompra_nroNotaCompra`),
  INDEX `fk_Produto_has_NotaCompra_NotaCompra1_idx` (`NotaCompra_nroNotaCompra` ASC),
  INDEX `fk_Produto_has_NotaCompra_Produto_idx` (`Produto_codProduto` ASC),
  CONSTRAINT `fk_Produto_has_NotaCompra_Produto`
    FOREIGN KEY (`Produto_codProduto`)
    REFERENCES `ministock`.`Produto` (`codProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_NotaCompra_NotaCompra1`
    FOREIGN KEY (`NotaCompra_nroNotaCompra`)
    REFERENCES `ministock`.`NotaCompra` (`nroNotaCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ministock`.`ItemVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ministock`.`ItemVenda` (
  `Produto_codProduto` INT NOT NULL,
  `NotaVenda_nroNotaVenda` INT NOT NULL,
  `qtdItemVenda` INT NOT NULL,
  `valorItemVenda` DOUBLE NOT NULL,
  PRIMARY KEY (`Produto_codProduto`, `NotaVenda_nroNotaVenda`),
  INDEX `fk_Produto_has_NotaVenda_NotaVenda1_idx` (`NotaVenda_nroNotaVenda` ASC),
  INDEX `fk_Produto_has_NotaVenda_Produto1_idx` (`Produto_codProduto` ASC),
  CONSTRAINT `fk_Produto_has_NotaVenda_Produto1`
    FOREIGN KEY (`Produto_codProduto`)
    REFERENCES `ministock`.`Produto` (`codProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_NotaVenda_NotaVenda1`
    FOREIGN KEY (`NotaVenda_nroNotaVenda`)
    REFERENCES `ministock`.`NotaVenda` (`nroNotaVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ministock`.`TipoProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ministock`.`TipoProduto` (
  `idTipoProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeTipoProduto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ministock`.`Produto_has_TipoProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ministock`.`Produto_has_TipoProduto` (
  `Produto_codProduto` INT NOT NULL,
  `TipoProduto_idTipoProduto` INT NOT NULL,
  PRIMARY KEY (`Produto_codProduto`, `TipoProduto_idTipoProduto`),
  INDEX `fk_Produto_has_TipoProduto_TipoProduto1_idx` (`TipoProduto_idTipoProduto` ASC),
  INDEX `fk_Produto_has_TipoProduto_Produto1_idx` (`Produto_codProduto` ASC),
  CONSTRAINT `fk_Produto_has_TipoProduto_Produto1`
    FOREIGN KEY (`Produto_codProduto`)
    REFERENCES `ministock`.`Produto` (`codProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_TipoProduto_TipoProduto1`
    FOREIGN KEY (`TipoProduto_idTipoProduto`)
    REFERENCES `ministock`.`TipoProduto` (`idTipoProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
